version: '3.8'

services:
  psgen-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Database=psgendb;Username=postgres;Password=postgres
      - Jwt__Key=your-development-key-at-least-32-characters-long
      - Jwt__Issuer=psgen-api
      - Jwt__Audience=psgen-clients
      - Jwt__ExpiryInDays=90
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=psgendb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres-data:
