version: '3.8'

services:
  psgen-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:      
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=psgen;Username=psgenuser;Password=your-password
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
